In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv(r"../input/playtennis/PlayTennis.csv")
data.head()

outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [3]:
# Converting string data to numeric data
le = LabelEncoder()
label = le.fit_transform(data['outlook'])
data["outlook"] = label

label2 = le.fit_transform(data["temp"])
data["temp"] = label2

label3 = le.fit_transform(data["humidity"])
data["humidity"] = label3

label4 = le.fit_transform(data["play"])
data["play"] = label4

label5 = le.fit_transform(data["windy"])
data["windy"] = label5

data.head()

outlook  temp  humidity  windy  play
0        2     1         0      0     0
1        2     1         0      1     0
2        0     1         0      0     1
3        1     2         0      0     1
4        1     0         1      0     1

> * In Naive Bayes alogorithm, we basically compute the result using conditional probablity
> * So the training stage includes calculating the conditional proabablity of a feature being a certain value for a given output
> * *Note the output in the data here is whether to play or not(0 or 1)*
> * Hence we calculate the probablity as follows
> * In column temp we have say values 0,1,2
> * So we calculate the conditional probablity of this feature given our output is 1 and o and store it for testing phase

In [4]:
test = [[2,0,0,1]]
test = np.array(test)
data = data.to_numpy()
print(data.shape)
print("Training data",data[:5,:])
print('test data',test)

(14, 5)
Training data [[2 1 0 0 0]
 [2 1 0 1 0]
 [0 1 0 0 1]
 [1 2 0 0 1]
 [1 0 1 0 1]]
test data [[2 0 0 1]]


In [5]:
# no we calculate the probablity of the features 
dummy=[]
for i in range(data.shape[1]-1):
    l3=[]
    for k in np.unique(data[:,i]):
        tt=0
        tf=0
        true=0
        false=0
        l2=[]
        for j in range(data.shape[0]):
            if(data[j,4]==1):
                tt+=1
            if(data[j,4]==0):
                tf+=1
            if(data[j,4]==1 and data[j,i]==k):
                true+=1
            if(data[j,4]==0 and data[j,i]==k):
                false+=1
        if(false==0):
            false = 1
            tf = tf+len(np.unique(data[:,4]))
        if(true==0):
            true = 1
            tt = tt+len(np.unique(data[:,4]))
        l2.append([true/tt,false/tf])
        l3.append(l2)
    dummy.append(l3)
print(dummy)

[[[[0.4444444444444444, 0.14285714285714285]], [[0.3333333333333333, 0.4]], [[0.2222222222222222, 0.6]]], [[[0.3333333333333333, 0.2]], [[0.2222222222222222, 0.4]], [[0.4444444444444444, 0.4]]], [[[0.3333333333333333, 0.8]], [[0.6666666666666666, 0.2]]], [[[0.6666666666666666, 0.4]], [[0.3333333333333333, 0.6]]]]


* *These are the values of the conditional probablities with respect to a given output*
* *Now there can be a case when the probablity is 0. So we need to smoothen the data*
* *This means we need to add a very small number to the numerator and denominator incase the false or true values are 0*

In [6]:
net_prob=[]

for i in np.unique(data[:,4]):
    p=1
    for j in range(len(test[0])): 
        prob = dummy[j][test[0][j]][0][i]
        p*=prob
    net_prob.append(p)
net_prob = np.array(net_prob)

x = np.argmax(net_prob)    #the output with the highest probablity will be selected
if(x==0):
    print("They will play")
else:
    print("They wouldnt play")

They wouldnt play
